### ISSUE TITLE
pretrained checkpoints couldn't be downloaded...

### ISSUE THREAD

**Issue by Yamato-01** [facebookresearch/InterWild#10]
Thanks for your work! I wonder whether the pretrained checkpoints could be downloaded. It seems that downloading is not available now.

**Comment by mks0601** [comment]
You can download from https://github.com/facebookresearch/InterWild#test

 If you want to test with pre-trained InterWild, download it from [here](https://drive.google.com/file/d/12temUVaIhrpUqw-zzXArqI6cm5aMfVWa/view?usp=share_link) and place it at `output/model_dump'.

**Comment by Yamato-01** [comment]
Thanks! It is available now.
