### ISSUE TITLE
Table 5 in the paper

### ISSUE THREAD

**Issue by redorangeyellowy** [facebookresearch/InterWild#11]
Hi, thank you for your wonderful research.

I wonder the meaning of left and right value of Table 5 as following:

![capture](https://github.com/facebookresearch/InterWild/assets/86509883/c0296491-7707-4224-97e4-073f823b3694)

I tried to find the difference of their meaning of MPVPE in your paper (including supplementary), but I cannot find it.

Would you explain the meaning of them, and the reason why they are different?

**Comment by mks0601** [comment]
Sorry for the unclear tables.. That was my mistake
You can refer to the caption of Table 2 instead: The left and right numbers for each setting represent errors
from single and interacting hand sequences, respectively.
