### ISSUE TITLE
Live Stream input

### ISSUE THREAD

**Issue by yqzhang99** [facebookresearch/InterWild#13]
Thank you for the amazing jobs.
The result of both 2.5D pose and 3D mesh is really impressive. 

But I am wondering if this work can be depolyed for the live stream? 
In other words, do you think the whole model can be run on real-time?

**Comment by mks0601** [comment]
Hi, it depends on your computational environment. If you're running with high-end GPUs, then, it might work in real-time.

**Comment by yqzhang99** [comment]
> Hi, it depends on your computational environment. If you're running with high-end GPUs, then, it might work in real-time.

Thank you for reply. I see.
Now I am trying use part of the whole architecture to predict only the 2.5D pose for faster prediction, like only using SHNet to predict 2.5D pose, and ignoring the TransNet and the part of 3D mesh.
Do you think it can work? I mean will the operation of ignoring the 3D mesh affect the prediction of 2.5 pose?
