### ISSUE TITLE
Size of GT 3D MANO fits

### ISSUE THREAD

**Issue by linjiangya** [facebookresearch/InterWild#26]
Thank you for the great dataset. I ran download_mano_fits.py to download GT MANO fits. The folder size after downloading is only 24GB, which is different from the description on your official website (83 GB after unzip.) Is this normal?

The frame id seems to have an interval=3.

**Comment by mks0601** [comment]
Hi linjiangya, thanks for reporting this. I confirmed that there are no missing files in the current released one, but I wrongly calculated the disk usage. I used `du -hs *` to calculate the folder size, but it seems I need to use `du -hs --apparent-size *`.

**Comment by mks0601** [comment]
I've updated all the storage in the website

**Comment by linjiangya** [comment]
Thank you for your prompt reply!

May I ask one more question? In the figure 4 of the Re:InterHand paper "A Dataset of Relighted 3D Interacting Hands", why does the hand model fit contain a wrist? Are you using another parametric model here instead of MANO?

**Comment by linjiangya** [comment]
> Hi, yeap that is 'Original fits' of https://mks0601.github.io/ReInterHand/.

Thank you! Is this 'original fits' mesh deformed from another type of parametric model? I think MANO does not contain such a former arm.

**Comment by mks0601** [comment]
yeap correct. It's our internal model.

**Comment by linjiangya** [comment]
> yeap correct. It's our internal model.

Oh, that explains it. Thank you so much:) 

Is there a plan to release this internal model? It looks more reasonable than MANO with an arm. :)

**Comment by mks0601** [comment]
We submitted a paper, and if it is accepted, we're going to release it

**Comment by linjiangya** [comment]
> We submitted a paper, and if it is accepted, we're going to release it

Thank you! Looking forward to this interesting model anyway. Merry Christmas to you.
