### ISSUE TITLE
About Re:InterHand, some file missing

### ISSUE THREAD

**Issue by aragakiyui611** [facebookresearch/InterWild#27]
`OSError: Fail to read ../data/ReInterHand/data/m--20221215--0949--RNS217--pilot--ProjectGoliathScript--Hands--two-hands/Mugsy_cameras/envmap_per_frame/images/400951/095967.png`
when I run the test set and the dataloader throws this error. I downloaded zip files of the dataset and unzip it few times but the file missing still exists.

**Comment by mks0601** [comment]
Hi, that is because envmap_per_frame is rendered in 5 fps, while frame_list.txt is in 30 fps. I changed data/ReInterHand/ReInterHand.py. Could you check again? Thanks!

**Comment by aragakiyui611** [comment]
Thank you! besides, [L72 of data/ReInterHand/ReInterHand.py](https://github.com/facebookresearch/InterWild/blob/9c8464a80d84888415d8c7cf827155ac1c6cf19c/data/ReInterHand/ReInterHand.py#L72), the int() lacks a ')'

**Comment by mks0601** [comment]
awesome. thanks!
