### ISSUE TITLE
About Interhand2.6M and MSCOCO dataset used in DetectNet

### ISSUE THREAD

**Issue by Shirley-olivia** [facebookresearch/InterWild#28]
Hi, I noticed that the inputs for DetectNet include the Interhand2.6M dataset and the MSCOCO dataset. However, the Interhand2.6M dataset mainly consists of hand images, while the MSCOCO dataset, after preprocessing, contains images of the entire body. There is a significant difference between these two input datasets. Does this imply that when training DetectNet for handbox, it heavily relies on the MSCOCO dataset?

**Comment by mks0601** [comment]
what do you mean by heavily relies on the mscoco dataset?

**Comment by Shirley-olivia** [comment]
If there is no MSCOCO dataset, the performance of HandboxNet trained on the InterHand2.6 dataset is quite poor on natural datasets. I noticed that during Mixed-Batch Training, the MSCOCO dataset is preprocessed to the size of body boxes, while the InterHand2.6 dataset itself is approximately the size of hand boxes. Therefore, the domain gap between them is not only in the background environment. As a result, I speculate that without the InterHand2.6M dataset, the training performance of DetectNet would not show a significant difference.
