### ISSUE TITLE
the accuracy of the 21 points labeling error 

### ISSUE THREAD

**Issue by ZYX-MLer** [facebookresearch/InterWild#31]
"I have visualized the marked results of key points in the reinter dataset and feel that the accuracy is not very high, especially for those blue points. What could be the issue?"

![1708330088860](https://github.com/facebookresearch/InterWild/assets/9656425/658d8cd5-99bb-4ed5-a4f5-618c74c6508b)

**Comment by mks0601** [comment]
That might be from the occlusions. But I think except for the left hand pinky root (blue), other blue points are reaosnable.
