### ISSUE TITLE
Visualization Demo Available?

### ISSUE THREAD

**Issue by txytju** [facebookresearch/InterWild#4]
Thanks for your great work and sharing code! Will you support visualization demo which plot hand mesh on original image? Thanks!

**Comment by mks0601** [comment]
Sorry you could try a demo following this instruction (https://github.com/facebookresearch/InterWild#demo), which produces 3D meshes of two hands, but overlaying on images is not supported at this moment. Will add that function soon

**Comment by mks0601** [comment]
Hi, visualization feature is added in here
https://github.com/facebookresearch/InterWild/blob/main/demo/demo.py
