### ISSUE TITLE
How can I just get joint lines of the picture with the model, I dont ecpect to render them. Thanks!

### ISSUE THREAD

**Issue by wefwwef4** [facebookresearch/InterWild#8]

**Comment by mks0601** [comment]
I'm not sure what you mean. could you ask again?

**Comment by wefwwef4** [comment]
> I'm not sure what you mean. could you ask again?
I only need the landmarks of the joint points, like in the previous interhand2.6m, without the need for rendering. What should I do to obtain this image with the model

**Comment by mks0601** [comment]
Do you need a 2D skeleton overlay on the input image?

**Comment by wefwwef4** [comment]
> Do you need a 2D skeleton overlay on the input image?
yeah

**Comment by mks0601** [comment]
You can run the demo again with newly pushed code and you can get visualized 2D skeleton in render folder
